'use client';
import {useState} from 'react';
import {ShieldCheck,Copy,Check,LockKeyhole,LogOut} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {api} from '@/lib/client-photo';
import type {Reward} from '@/lib/reward-catalog';
import RewardLook from './reward-look';
import AdminLevel from './admin-level';
type Item=Reward&{number:number;code?:string;redeemed_at?:string|null};type Data={authenticated:boolean;rewards:Item[]};
export default function AdminPanel({onRewards}:{onRewards:()=>void}){
 const [open,setOpen]=useState(false),[data,setData]=useState<Data|null>(null),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState('');
 async function show(){setOpen(true);setError('');setPassword('');setBusy(true);try{setData(await api<Data>('/api/admin'));}catch(e){setError(e instanceof Error?e.message:'Laden fehlgeschlagen.');}finally{setBusy(false);}}
 async function login(){if(busy)return;setBusy(true);setError('');try{setData(await api<Data>('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}));setPassword('');window.dispatchEvent(new Event('reward-updated'));}catch(e){setError(e instanceof Error?e.message:'Anmeldung fehlgeschlagen.');}finally{setBusy(false);}}
 async function logout(){setBusy(true);try{await api('/api/admin',{method:'DELETE'});setData({authenticated:false,rewards:[]});}catch(e){setError(e instanceof Error?e.message:'Abmelden fehlgeschlagen.');}finally{setBusy(false);}}
 async function copy(code:string){try{await navigator.clipboard.writeText(code);setCopied(code);}catch{setError('Markiere deinen Code zum manuellen Kopieren.');}}
 return <><Button variant="ghost" className="admin-trigger" onClick={show}><ShieldCheck size={19}/><span>Admin-Panel</span></Button><Dialog open={open} onOpenChange={v=>{if(!busy){setOpen(v);setPassword('');}}}><DialogContent className="admin-dialog" onEscapeKeyDown={e=>{if(busy)e.preventDefault();}} onInteractOutside={e=>{if(busy)e.preventDefault();}}><DialogTitle>Admin-Panel</DialogTitle><DialogDescription>{data?.authenticated?'Alle Geschenk-Codes. Jedes Extra wird erst nach dem Einlösen im Rewards-Menü verfügbar.':'Mit deinem Passwort erhältst du Zugriff auf die Geschenk-Codes.'}</DialogDescription>{!data?.authenticated?<form className="admin-login entry-fields" onSubmit={e=>{e.preventDefault();void login();}}><LockKeyhole size={28}/><label htmlFor="admin-password">Passwort</label><Input id="admin-password" type="password" inputMode="numeric" value={password} maxLength={100} onChange={e=>setPassword(e.target.value)} autoComplete="off" required/><Button type="submit" disabled={busy||!password}>{busy?'Wird geprüft…':'Codes freischalten'}</Button></form>:<><AdminLevel/><div className="admin-toolbar"><Button disabled={busy} onClick={login}>Geschenk-Codes bereitstellen</Button><span>{data.rewards.filter(r=>r.redeemed_at).length} / {data.rewards.length} eingelöst</span><Button variant="ghost" disabled={busy} onClick={logout}><LogOut size={16}/>Sperren</Button></div><div className="admin-reward-grid">{data.rewards.map(r=><article className="admin-reward-card" key={r.key}><span className="gift-number">GESCHENK {String(r.number).padStart(2,'0')}</span>{['frame','name'].includes(r.type)?<RewardLook name="Kiro Champion" frame={r.type==='frame'?r.key:'default'} nameStyle={r.type==='name'?r.key:'default'}/>:<div className="cosmetic-preview">{r.type==='photo'?'Dein Foto':r.type==='kiro'?'KIRO ★':'CHAMPION ★'}</div>}<h3>{r.label}</h3>{r.redeemed_at?<span className="redeemed"><Check size={15}/>Eingelöst</span>:r.code?<><code>{r.code}</code><Button variant="ghost" onClick={()=>copy(r.code!)}><Copy size={15}/>{copied===r.code?'Kopiert':'Code kopieren'}</Button></>:<p>Code noch nicht verfügbar.</p>}</article>)}</div><Button className="admin-to-rewards" onClick={()=>{setOpen(false);onRewards();}}>Codes unter Rewards einlösen</Button></>}{error&&<p className="error" role="alert">{error}</p>}</DialogContent></Dialog></>;
}
