'use client';
import {useState,useEffect} from 'react';
import {CircleHelp} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import RewardsHelp from './rewards-help';
const guides:Record<string,{title:string;intro:string;steps:[string,string][]}>={
 kiro:{title:'Dein Assistent Kiro',intro:'Schreiben, sprechen und eine Kamera-Vorschau ausprobieren.',steps:[['Schreiben','Unten deine Frage eingeben. Kiro antwortet erst, wenn die KI-Verbindung eingerichtet ist.'],['Live-Modus','Das Mikrofon öffnet die animierte Vorschau. Die Kamera zeigt dich auf deinem Gerät. Aktuell gibt es keine KI-Antworten und keine Übungsbewertung.']]},
 nutrition:{title:'Deine Ernährung im Blick',intro:'Mahlzeiten festhalten und Wochen ansehen.',steps:[['Mahlzeit hinzufügen','Ein Foto auswählen oder aufnehmen und kurz beschreiben, was du gegessen hast.'],['Deine Woche','Zwischen den Wochen wechseln und Einträge ansehen oder löschen. KI-Auswertungen brauchen eine aktive KI-Verbindung.']]},
 muscle:{title:'Dein Training',intro:'Wähle einen Bereich und trainiere in deinem Tempo.',steps:[['Übungen ansehen','Ein Bereich zeigt dir Zeichnungen, Bewegungsablauf und Einstiegsvorschläge. Mit „Zurück zur Auswahl“ wechselst du den Bereich.'],['Passend für dich','Altersgruppe im Profil ändern. Weitere Technikvarianten schaltest du bei Level 3, 5, 10, 20 und 30 frei. Gesperrte Varianten zeigen das benötigte Level. Das Level bewertet nicht deine körperliche Belastbarkeit.']]},
 plan:{title:'So funktioniert dein Plan',intro:'Dein Kalender für Training und regelmäßige Bewegung.',steps:[['Ein übersichtlicher Kalender','Du siehst das aktuelle Jahr und vier weitere Jahre, jetzt bis Ende 2030. Jedes neue Jahr erweitert den Kalender um ein weiteres Jahr; das Vorjahr verschwindet aus der Ansicht.'],['Tag und Uhrzeit wählen','Tippe auf einen Tag, lege deinen Trainingsbereich und eine Uhrzeit fest. Alle Termine nutzen deutsche Zeit (Europe/Berlin). Du kannst sie bearbeiten, abhaken oder löschen.'],['Zur richtigen Zeit starten','Wenn Fit geöffnet ist, erscheint „Beginn mit dem Training“. Browser-Mitteilungen kannst du zusätzlich aktivieren. Bei geschlossener App nutze „Handy-Kalender“ und aktiviere dort die Erinnerung.'],['Mit Kiro planen','Bereite eine Planungsfrage vor. Sobald die KI verbunden ist, hilft Kiro beim Verteilen deiner Einheiten. Vorschläge werden erst nach deiner Entscheidung als Termine gespeichert.']]},
 profile:{title:'Dein Profil',intro:'Dein Name, dein Look und deine Einstellungen an einem Ort.',steps:[['Oben rechts erreichbar','Dein Profil bleibt in jedem Menü sichtbar. Nach „Profil speichern“ aktualisieren sich Name, Foto und Rahmen auch oben rechts.'],['Champion-Look','Eingelöste Extras auswählen und speichern. App-Level und Geschenke bleiben voneinander unabhängig.'],['Einstellungen','Hier änderst du deine Altersgruppe oder setzt alle deine Daten zurück, einschließlich deines Plans.']]}
};
export default function MenuHelp({menu,paused}:{menu:string;paused:boolean}){
 const [open,setOpen]=useState(false);
 useEffect(()=>{setOpen(false);if(paused)return;try{if(!localStorage.getItem('fit-help-v2-'+menu)){setOpen(true);localStorage.setItem('fit-help-v2-'+menu,'seen');}}catch{}},[menu,paused]);
 const guide=guides[menu];
 return <><button className="menu-help-button" aria-label={'Hilfe für '+(guide?.title||'Geschenke')} onClick={()=>setOpen(true)}><CircleHelp size={22}/></button>{menu==='rewards'?<RewardsHelp open={open} onOpenChange={setOpen}/>:<Dialog open={open} onOpenChange={setOpen}><DialogContent className="rewards-help-dialog"><DialogTitle>{guide?.title}</DialogTitle><DialogDescription>{guide?.intro}</DialogDescription><div className="help-steps">{guide?.steps.map(([title,text])=><article key={title}><div><h2>{title}</h2><p>{text}</p></div></article>)}</div><p className="help-privacy">Diese Erklärung erscheint beim ersten Besuch auf diesem Gerät. Das Fragezeichen öffnet sie jederzeit erneut.</p></DialogContent></Dialog>}</>;
}
