'use client';
import {useState,useEffect,useRef} from 'react';
import {UserRound,Camera,LockKeyhole,Check,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {api,preparePhoto} from '@/lib/client-photo';
import RewardLook from './reward-look';
import AccountSettings from './account-settings';
import ResetAccount from './reset-account';
import ProfileLevel from './profile-level';
import ChampionSettings from './champion-settings';
import {ageRange} from '@/lib/exercises';
type Unlock={reward:string;label:string;month:string};type Data={profile:{name:string;nameStyle:string;frame:string;hasPhoto:boolean;updatedAt:string};unlocks:Unlock[]};
export default function Profile({age,onEditAge}:{age:number|null;onEditAge:()=>void}){
 const [data,setData]=useState<Data|null>(null),[name,setName]=useState(''),[nameStyle,setNameStyle]=useState('default'),[frame,setFrame]=useState('default'),[photo,setPhoto]=useState<File|null>(null),[preview,setPreview]=useState(''),[error,setError]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);const file=useRef<HTMLInputElement>(null);
 async function load(){setLoading(true);try{const d=await api<Data>('/api/profile');setData(d);setName(d.profile.name);setNameStyle(d.profile.nameStyle);setFrame(d.profile.frame);setError('');}catch(e){setError(e instanceof Error?e.message:'Laden fehlgeschlagen.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(!photo){setPreview('');return;}const url=URL.createObjectURL(photo);setPreview(url);return()=>URL.revokeObjectURL(url);},[photo]);
 async function save(){if(busy)return;setBusy(true);setError('');setNote('');try{const f=new FormData();f.append('name',name);f.append('nameStyle',nameStyle);f.append('frame',frame);if(photo)f.append('photo',await preparePhoto(photo));await api('/api/profile',{method:'POST',body:f});setPhoto(null);await load();setNote('Profil gespeichert.');window.dispatchEvent(new Event('profile-updated'));}catch(e){setError(e instanceof Error?e.message:'Speichern fehlgeschlagen.');}finally{setBusy(false);}}
 async function removePhoto(){setBusy(true);setError('');try{await api('/api/profile/photo',{method:'DELETE'});setPhoto(null);await load();setNote('Profilfoto entfernt.');window.dispatchEvent(new Event('profile-updated'));}catch(e){setError(e instanceof Error?e.message:'Löschen fehlgeschlagen.');}finally{setBusy(false);}}
 const unlockedPhoto=data?.unlocks.some(u=>u.reward.startsWith('photo:'));
 return <section className="section-page profile"><div className="section-heading"><span className="eyebrow">DEIN BEREICH</span><h1>Profil</h1></div>{loading&&!data?<p className="muted">Profil wird geladen…</p>:data&&<><ProfileLevel/><div className="profile-preview"><RewardLook name={name||'Dein Name'} frame={frame} nameStyle={nameStyle} photoSrc={preview||(data.profile.hasPhoto?'/api/profile/photo?v='+encodeURIComponent(data.profile.updatedAt):undefined)}/><button className="age-pill" onClick={onEditAge}>{age===null?'Altersgruppe wählen':ageRange(age)} · Ändern</button></div><form className="profile-edit entry-fields" onSubmit={e=>{e.preventDefault();void save();}}><h2>Dein Look</h2><label htmlFor="profile-name">Anzeigename</label><Input id="profile-name" required maxLength={30} value={name} onChange={e=>setName(e.target.value)}/><label htmlFor="profile-name-style">Namensstil</label><select id="profile-name-style" value={nameStyle} onChange={e=>setNameStyle(e.target.value)}><option value="default">Standard</option>{data.unlocks.filter(u=>u.reward.startsWith('name:')).map(u=><option key={u.reward} value={u.reward}>{u.label}</option>)}</select><label htmlFor="profile-frame">Profilrahmen</label><select id="profile-frame" value={frame} onChange={e=>setFrame(e.target.value)}><option value="default">Standard</option>{data.unlocks.filter(u=>u.reward.startsWith('frame:')).map(u=><option key={u.reward} value={u.reward}>{u.label}</option>)}</select><label>Profilfoto aus deinen Bildern</label>{unlockedPhoto?<><Button type="button" className="choose-photo" disabled={busy} onClick={()=>file.current?.click()}><Camera size={18}/>{photo?'Anderes Foto wählen':'Profilfoto auswählen'}</Button><input ref={file} type="file" accept="image/*" hidden onChange={e=>{setPhoto(e.target.files?.[0]||null);e.target.value='';}}/>{data.profile.hasPhoto&&<Button type="button" variant="ghost" className="delete-photo" disabled={busy} onClick={removePhoto}><Trash2 size={15}/>Profilfoto entfernen</Button>}</>:<p className="locked-line"><LockKeyhole size={17}/>Mit einem Profilfoto-Reward freischaltbar.</p>}<Button type="submit" className="add-meal" disabled={busy}>{busy?'Wird gespeichert…':'Profil speichern'}</Button></form><ChampionSettings unlocks={data.unlocks}/><div className="feed-heading"><h2>Freigeschaltete Extras</h2><span>{data.unlocks.length}</span></div>{data.unlocks.length===0?<p className="muted">Noch keine Extras. Löse deinen ersten Monatscode ein.</p>:<div className="unlocks">{data.unlocks.map(u=><div key={u.reward}><Check size={18}/>{u.label}</div>)}</div>}</>}{error&&<div className="error" role="alert">{error}{!data&&<Button variant="ghost" onClick={load}>Erneut laden</Button>}</div>}{note&&<p className="save-note" role="status">{note}</p>}<AccountSettings/><ResetAccount disabled={busy}/></section>;
}
