'use client';
import {useState} from 'react';
import {browserClient} from '@/lib/supabase-browser';
import './login.css';
export default function Login(){
 const [mode,setMode]=useState<'login'|'signup'|'reset'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const client=browserClient();
 if(mode==='reset'){const r=await client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/auth/callback?next=/password'});if(r.error)throw r.error;setMessage('Falls ein Konto vorhanden ist, erhältst du eine E-Mail zum Zurücksetzen.');}
 else if(mode==='signup'){const r=await client.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/auth/callback'}});if(r.error)throw r.error;if(r.data.session)location.replace('/');else setMessage('Prüfe dein E-Mail-Postfach und bestätige dein Konto. Danach kannst du dich hier anmelden.');}
 else{const r=await client.auth.signInWithPassword({email,password});if(r.error)throw r.error;for(const key of Object.keys(localStorage))if(key.startsWith('fit-'))localStorage.removeItem(key);location.replace('/');}
 }catch(e){const raw=e instanceof Error?e.message:'';setError(/Invalid login/.test(raw)?'E-Mail oder Passwort stimmt nicht.':/Email not confirmed/.test(raw)?'Bitte bestätige zuerst deine E-Mail-Adresse.':/rate limit/i.test(raw)?'Zu viele Versuche. Bitte warte kurz und versuche es erneut.':raw||'Anmeldung fehlgeschlagen.');}finally{setBusy(false);}}
 return <main className="login-page"><section className="login-card"><a className="login-brand" href="/login"><img src="/fit-icon.jpg" alt="Fit"/>fit<span>.</span></a><span className="eyebrow">DEIN TRAINING. DEIN FORTSCHRITT.</span><h1>{mode==='signup'?'Dein eigenes Fit.':mode==='reset'?'Passwort vergessen?':'Willkommen zurück.'}</h1><p>Dein Profil, dein Trainingsplan und deine Fotos bleiben in deinem persönlichen Konto.</p><form onSubmit={submit}><label htmlFor="email">E-Mail</label><input id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/>{mode!=='reset'&&<><label htmlFor="password">Passwort</label><input id="password" type="password" autoComplete={mode==='signup'?'new-password':'current-password'} minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/>{mode==='signup'&&<small>Mindestens 8 Zeichen.</small>}</>}{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="save-note" role="status">{message}</p>}<button className="login-submit" disabled={busy}>{busy?'Einen Moment…':mode==='signup'?'Konto erstellen':mode==='reset'?'Link anfordern':'Anmelden'}</button></form><button className="login-switch" onClick={()=>{setMode(mode==='login'?'signup':'login');setMessage('');setError('');}}>{mode==='login'?'Neu bei Fit? Konto erstellen':'Zur Anmeldung'}</button>{mode==='login'&&<button className="login-switch" onClick={()=>setMode('reset')}>Passwort vergessen?</button>}<small className="login-note">Ohne ChatGPT-Konto nutzbar. Anmeldung über Supabase.</small></section></main>;
}
